name: Build only
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            path: 'mod'

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet build
        working-directory: mod
        run: dotnet build "Source\RunAndGun\RunAndGun.csproj" --configuration Release

      - name: Cleanup
        working-directory: mod
        run: |
            rm -rf .git
            rm -rf .vs
            rm -rf .github/workflows
            rm -rf .github
            rm -rf .gitignore
            rm -rf .gitattributes
            rm -rf README.md
            sudo rm -rf Workshop
            find . -type d -name "obj" -exec rm -rf {} +

      - name: Upload DLL as artifact
        uses: actions/upload-artifact@v4
        with:
          name: RunAndGun_DLL
          path: /home/runner/work/RunAndGun/RunAndGun/mod/Source/RunAndGun/bin/Release/RunAndGun.dll

